### ISSUE TITLE
open source

### ISSUE THREAD

**Issue by xoceunder** [zgelici/FOS-Streaming-v1#10]
It is no longer as open source code obfuscate litters
@zgelici

**Comment by zgelici** [comment]
Because of one script?

You can replace the code with your own code. because you already have the data?

@xoceunder

**Comment by xoceunder** [comment]
This http://fos-streaming.com/install.php.1 

no one knows that you are installing

@zgelici

**Comment by zgelici** [comment]
Yes i know, in the new update i think i will make the install.php readable (not obfuscated)
