### ISSUE TITLE
channel live stream is late 3 minutes

### ISSUE THREAD

**Issue by stole204** [zgelici/FOS-Streaming-v1#15]
Hi all,

I have tbs card which streams directly to VLC, then VLC transcode output to FOS Panel. Streams plays ok, but they late 3 minutes.

I tried the link directly from VLC transcoder it works ok, without late.

Server installed with these :

Ubuntu 14.04.3 LTS 64 bit
nginx version: nginx/1.9.2
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Fos panel installed yesterday, latest version.

**Comment by zgelici** [comment]
Hi stole204,

There can be a lot of reasons of late timing. One of these reasons can be caused by vlc. Try once open it directly in fos and transcode it from there and check it again.

**Comment by zgelici** [comment]
By the way we are using hls(m3u8) this delay is also max 30s
