### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by idealsat** [zgelici/FOS-Streaming-v1#17]
Hi

I install fos streaming.

1.There is issue when stop stream manually and again start then it cant connect to server correctly some time its shown old video.

2.If video coming from vlc ex ( http://x.x.x.x:8080 ) when we reboot system its connect correctly but after one or two minute its leave connection from vlc stream.

when start manually then it cant connect and play old last minute video.

Hope these issues solve soon.

Thanks for Great work and software.

**Comment by andykimpe** [comment]
hi
try activate reapet one vlc
