### ISSUE TITLE
open source

### ISSUE THREAD

**Issue by xoceunder** [zgelici/FOS-Streaming-v1#18]
the system is not open source because they contain eval (gzuncompress(base64_decode(

I would like to have it open in order to modify and improve code

**Comment by xoceunder** [comment]
this https://github.com/zgelici/FOS-Streaming-v1/blob/eab71916e906995baeb5109484c2afca384c507e/stream.php

@zgelici

**Comment by zgelici** [comment]
If you want to improve things, you can do that. If you want to improve stream.php. you can build it your own. If you open the same issue. Than i dont response to it. Good luck. I have a reason for that. But i dont need to give that.
