### ISSUE TITLE
few bugs

### ISSUE THREAD

**Issue by edyee** [zgelici/FOS-Streaming-v1#2]
1:  Dashboard button not work
2: in streams Mass start / stop / delete dont work and also select all dont work
3: copy copy default 1 / 2 dont play the streams

**Comment by edyee** [comment]
even transcode dont work as well but transcode was working in old panel

**Comment by zgelici** [comment]
thanks, i'm going to check it

**Comment by zgelici** [comment]
Hello Edyee

1. Fixed
2. Select all -> checked (working)
2. Mass start/stop/delete working
3.working

I think you didnt install it with the new install

Soon we will place the installation instructions in the readme of github.

**Comment by edyee** [comment]
yes ..now dashboard works , 3 works but 2 still dont work for me
