### ISSUE TITLE
Error installation, please help

### ISSUE THREAD

**Issue by Guims** [zgelici/FOS-Streaming-v1#21]
Hello,

I come to you because I found a mistake at the beginning of the installation on a newly installed server, I copy you the message that is displayed on putty:

/////////////////////////////////////////////////////
 Report this problem on www.fos-streaming.com
PHP Notice:  Undefined index: DISTRIB_ID in /tmp/install.php(1) : eval()'d code on line 1
 Distro:
 PHP Notice:  Undefined index: DISTRIB_RELEASE in /tmp/install.php(1) : eval()'d code on line 1
Version:
 PHP Notice:  Undefined index: DISTRIB_CODENAME in /tmp/install.php(1) : eval()'d code on line 1
Codename:
 PHP Notice:  Undefined index: DISTRIB_DESCRIPTION in /tmp/install.php(1) : eval()'d code on line 1
Discription:
 x86_64
/////////////////////////////////////////////////////

Thank you in advance for your assistance.

**Comment by zgelici** [comment]
try this install file
https://github.com/zgelici/FOS-Streaming-v1/blob/master/install_panel.php
or you download this script and remove this part:
if (trim($release_info["DISTRIB_ID"]) == "Ubuntu") {
    echo "]PASS \n";
}
elseif (trim($release_info["DISTRIB_ID"]) == "Debian") {
    echo "]PASS \n";
}
else {
    echo "]FAIL \n";
    echo "///////////////////////////////////////////////////// \n";
    echo " Report this problem on www.fos-streaming.com \n";
    echo ' Distro: ' . $release_info["DISTRIB_ID"] . "\n ";
    echo 'Version: ' . $release_info["DISTRIB_RELEASE"]  . "\n ";
    echo 'Codename: ' . $release_info["DISTRIB_CODENAME"]  . "\n ";
    echo 'Discription: ' . $release_info["DISTRIB_DESCRIPTION"] . "\n ";
    echo $arch;
    echo "///////////////////////////////////////////////////// \n";
    die();
}

**Comment by Guims** [comment]
Hello and thank you for your reply , removing the code after the installation starts , but I get errors :

1. [Distribution Detection:]  [############2. [Arch Detection:]          [############]PASS
3. [Installing needed files:] [############]PASS
4. [FOS-Panel Installation:]  [########/home/fos-streaming/fos/php/sbin/php-fpm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /home/fos-streaming/fos/php/sbin/php-fpm)
/home/fos-streaming/fos/php/sbin/php-fpm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/fos-streaming/fos/php/sbin/php-fpm)
/home/fos-streaming/fos/php/sbin/php-fpm: /usr/lib/x86_64-linux-gnu/libxml2.so.2: version `LIBXML2_2.9.0' not found (required by /home/fos-streaming/fos/php/sbin/php-fpm)
/home/fos-streaming/fos/nginx/sbin/nginx_fos: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/fos-streaming/fos/nginx/sbin/nginx_fos)
#####]PASS

So to install the latest versions of libc6 and libxml2 , there are the deposits "testing" in sources.list
then restarts the command: apt- get install libc6 libxml2

and now I have no error if I run two commands:

/home/fos-streaming/fos/php/sbin/php-fpm
/home/fos-streaming/fos/nginx/sbin/nginx_fos

well I get my login page, I get home admin / admin and when I click connect , I get a blank page, or see how is the problem please ?

**Comment by Guims** [comment]
Good evening,

I managed the installation !!! yeaaaaaaaaaaahhhhhhh ^^

For those who have the same problem and you have a wheezy distribution
you have to edit your sources.list to add

sid main deb http://ftp.debian.org/debian
deb http://packages.dotdeb.org wheezy all
deb- src all wheezy http://packages.dotdeb.org
deb http://packages.dotdeb.org wheezy - php55 all
deb- src - http://packages.dotdeb.org wheezy php55 all

then

wget http://www.dotdeb.org/dotdeb.gpg
apt- key add dotdeb.gpg

then

apt-get update && apt- get install -y libc6 libxml2

then delete / comment sid repository in your sources.list " #deb http://ftp.debian.org/debian hand sid " to avoid further problems

and finally , install php 5.5 so

apt- get dist-upgrade
_______________________________
_______________________________

Now I encounter warning during installation with composing, I show you this:
cd /home/fos-streaming/fos/www/  
php /usr/src/composer.phar install

Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing symfony/polyfill-mbstring (v1.0.0)
    Downloading: 100%

  - Installing symfony/translation (v3.0.0)
    Downloading: 100%

  - Installing nesbot/carbon (1.21.0)
    Downloading: 100%

  - Installing danielstjules/stringy (1.10.0)
    Downloading: 100%

  - Installing doctrine/inflector (v1.1.0)
    Downloading: 100%

  - Installing illuminate/contracts (v5.1.25)
    Downloading: 100%

  - Installing illuminate/support (v5.1.25)
    Downloading: 100%

  - Installing illuminate/container (v5.1.25)
    Downloading: 100%

  - Installing illuminate/database (v5.1.25)
    Downloading: 100%

  - Installing illuminate/events (v5.1.25)
    Downloading: 100%

  - Installing symfony/finder (v2.7.7)
    Downloading: 100%

  - Installing illuminate/filesystem (v5.1.25)
    Downloading: 100%

  - Installing illuminate/view (v5.1.25)
    Downloading: 100%

  - Installing philo/laravel-blade (v3.1)
    Downloading: 100%

  - Installing filp/whoops (1.1.10)
    Downloading: 100%

symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
symfony/translation suggests installing psr/log (To use logging capability in translator)
illuminate/support suggests installing jeremeamia/superclosure (Required to be able to serialize closures (~2.0).)
illuminate/support suggests installing paragonie/random_compat (Provides a compatible interface like PHP7's random_bytes() in PHP 5 projects (~1.1).)
illuminate/support suggests installing symfony/var-dumper (Improves the dd function (2.7.*).)
illuminate/database suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.4).)
illuminate/database suggests installing fzaninotto/faker (Required to use the eloquent factory builder (~1.4).)
illuminate/database suggests installing illuminate/console (Required to use the database commands (5.1.*).)
illuminate/database suggests installing illuminate/pagination (Required to paginate the result set (5.1.*).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (~1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)


is it normal that is written in the end?

**Comment by zgelici** [comment]
I think that is right..

**Comment by Stefanoz45** [comment]
Hi, I fixed this problem. 
https://gist.github.com/Stefanoz45/162011f42bb67e7c719bbf087d65a36b

**Comment by zgelici** [comment]
Stefanoz45 thanks for your fix

**Comment by Stefanoz45** [comment]
You are welcome. I have written an email in to report some bug.

**Comment by iPrinz96** [comment]
Hello.
i have a big Problem with curl.

curl: (7) Failed to connect port 8000 ......

With the old FOS-Streaming Panel its work. But the manage_user.php is bugged.
Than i will install FOS-Streaming-v1 but i become every this fucking Problem.
i have test it with ubuntu, Debian 6, 7 & 8. And on my Raspberry PI.
Of my Raspberry pi is the same Problem how of my KVM Server..
Please help :)

**Comment by Stefanoz45** [comment]
Hi, make sure the server is running using
```
/etc/init.d/nginx status
```

The panel is buggy, a lot of blank pages,  I'm trying to resolve it.
