### ISSUE TITLE
help to protect M3U8

### ISSUE THREAD

**Issue by iksprteam** [zgelici/FOS-Streaming-v1#23]
I want to see if they can help me to protect my url M3U8 to my system that I'm creating I see you managed to get it going with this but I'm trying not work for me

<?php
					$context = stream_context_create ( array ('http' => array ('timeout' => 3.0 )) );
					
					$url = "http://localhost:8000/hls/".$name.".m3u8";

					$file_handler = fopen ( $url, "rb", false, $context ) or exit ( "Stream Not Working m3u8" );
					
					foreach ( $http_response_header as $h ) {
						header ( $h );
					}
					
					while ( ! feof ( $file_handler ) ) {
						
						if ($client_allowed_bandwidth != 0 and $bytes > $client_allowed_bandwidth) {
							break;
						}
						
						$response = stream_get_line ( $file_handler, 8192 );
						
						$bytes += strlen ( $response );
						echo $response;
					}
					@fclose ( $file_handler );

@zgelici

**Comment by zgelici** [comment]
I think you can protect your folder with this: 

location ^~ /hls/ {
    allow localhost;
    deny  all;
}

Good luck

**Comment by iksprteam** [comment]
so I have but the problem is that it opens in a player and shoot me the url of .ts

**Comment by zgelici** [comment]
ok, but when you block it, than they cant read that ts files. because your the player will still read the ts files from the hls folder.

**Comment by iksprteam** [comment]
php code that recommended me to open the M3U8 is that your system tried and I liked that only opens the link channel and open the channel without mostral the source if I have to pay for their help gladly friend

**Comment by zgelici** [comment]
but the stream.php already works with FOS-Streaming. Why you dont use that?

**Comment by iksprteam** [comment]
if it works is that I'm creating a system for personal use to control my striming

**Comment by iksprteam** [comment]
this 

<?php
$fichero = 'test-4492.ts';
$reqpath = strip_tags($fichero);
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Cache-Control: no-store, no-cache,must-revalidate");
header("Cache-Control: post-check=0, pre-check=0",false);
header("Pragma: no-cache");
header('Content-type:application/force-download');
if (strpos($_GET['file'],".ts")>1) header("Content-type: video/MP2T");
if (strpos($_GET['file'],".m3u8")>1) header("Content-type: application/x-mpegURL");
@readfile("/tmp/hls/".$reqpath);

I opened the .ts file without showing the origin but does not work I .m3u8

**Comment by iksprteam** [comment]
Might you help me

**Comment by iksprteam** [comment]
this

<?php
function readfile_chunked($filename,$retbytes=true) {
   $chunksize = 1*(1024*1024); // how many bytes per chunk
   $buffer = '';
   $cnt =0;
   // $handle = fopen($filename, 'rb');
   $handle = fopen($filename, 'rb');
   if ($handle === false) {
       return false;
   }
   while (!feof($handle)) {
       $buffer = fread($handle, $chunksize);
       echo $buffer;
       ob_flush();
       flush();
       if ($retbytes) {
           $cnt += strlen($buffer);
       }
   }
       $status = fclose($handle);
   if ($retbytes && $status) {
       return $cnt; // return num. bytes delivered like readfile() does.
   }
   return $status;

} 

$file = strip_tags(readfile_chunked('/tmp/hls/wapa.m3u8'));
header("Expires: Mon, 26 Jul 2015 05:00:00 GMT");
header("Cache-Control: no-store, no-cache,must-revalidate");
header("Cache-Control: post-check=0, pre-check=0",false);
header("Pragma: no-cache");
// header('Content-type:application/force-download');
$totalFileSize = filesize($file);
header("Content-Length: ".$totalFileSize);
$end = $totalFileSize - 1;
header("Content-Range: bytes 0-$end/$totalFileSize");
header("Content-type: video/MP2T");
@readfile($file);

?>
@zgelici
