### ISSUE TITLE
How about add VoD

### ISSUE THREAD

**Issue by nojom** [zgelici/FOS-Streaming-v1#24]
hello

How about add
VoD Support. Stream VoD Channels
and 
supported more Stream inputs 
RTMP
UTP
RTP
RTSP
and more
thank you very much 
sorry for my english

**Comment by andykimpe** [comment]
hi

for udp and rtp use https://sourceforge.net/projects/udpxy/

for rtsp use https://sourceforge.net/p/iptv2rtsp-proxy/wiki/Home/

for rtmp use rtmpdump
