### ISSUE TITLE
restream from local rtmp

### ISSUE THREAD

**Issue by crottolo** [zgelici/FOS-Streaming-v1#25]
Congratulations on a job well done with IPTV panel, we have a request to make because the normal configuration does not work:

I have an encoder adobe publishing on the server with installed IPTV panel.
I wish I could share the stream with members through the same.
the problem by inserting rtmp: //127.0.0.1: 1935 / test / 111 or rtmp: //ip.my.ser.ver: 1935 / test / 111 can not reshare the channel.
 this is my conf:
user  root;
worker_processes  auto;
worker_rlimit_nofile 15000;

error_log  logs/error.log debug;

events {
     worker_connections 15000;
     multi_accept on;
  use epoll;
 }

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
                listen 8000;
                root /usr/local/nginx/html/;
                index index.php index.html index.htm;
                server_tokens off;
                chunked_transfer_encoding off;
                rewrite  ^/(.*)/(.*)/(.*)$ /stream.php?username=$1&password=$2&stream=$3 break;

 location ~ \.php$ {
                        try_files $uri =404;
                        fastcgi_index index.php;
                        fastcgi_pass unix:/var/run/php5-fpm.sock;
                        include fastcgi_params;
                        fastcgi_keep_conn on;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
                }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;

      		  }

        # This URL provides RTMP statistics in XML
        location /stat {
            rtmp_stat all;

            # Use this stylesheet to view XML as web page
            # in browser
            rtmp_stat_stylesheet stat.xsl;
            #allow 127.0.0.1;
        }

        location /stat.xsl {
            # XML stylesheet to view RTMP stats.
            # Copy stat.xsl wherever you want
            # and put the full directory path here
            root /usr/local/nginx/html;
        }
   

 }
}

rtmp {
    server {
        listen 1935;
        ping 30s;
        notify_method get;

        application rtmp {
            live on;
        }

        # TV mode: one publisher, many subscribers
        application test {

            # enable live streaming
            live on;

            # record first 1K of stream
            record all;
            record_path /tmp/av;
            record_max_size 1K;

            # append current timestamp to each flv
            record_unique on;

            # publish only from localhost
            #allow publish 127.0.0.1;
            #deny publish all;

            #allow play all;
   

        }

    }
}

**Comment by zgelici** [comment]
stream to
rtmp: /yourserverip:1935/rtmp/name
opening in your panel rtmp://127.0.0.1:1935/rtmp/name

you can also try

stream to
rtmp: /yourserverip:1935/test/name
opening in your panel rtmp://127.0.0.1:1935/test/name

**Comment by crottolo** [comment]
it's work fine.
thanks thanks
