### ISSUE TITLE
Bugs!

### ISSUE THREAD

**Issue by Goldtrak** [zgelici/FOS-Streaming-v1#3]
![fos-stream-not coorect](https://cloud.githubusercontent.com/assets/15348683/10768989/1e549e4c-7ce4-11e5-9bba-3cd642eb4fda.PNG)

Hi, thanks for your work.

About the issue is all images hey are highly inclined to the right and you can not see everything in the panel.

Could you check please?

thanks

Best regards

**Comment by Goldtrak** [comment]
hi, i found the issue is compatible mode.

I  try now with Microsoft EDGE and work's perfect.

But with Mozilla firefox 41.0.2 dont work.

Best regards

**Comment by zgelici** [comment]
Hello Goldtrak,

Thanks for reporting it. We will find a solution to fix it.

Best Regards

**Comment by zgelici** [comment]
Hi Goldtrak,

I pushed a new version to github. You need the panel. I changed the views.

Best Regards

**Comment by Goldtrak** [comment]
Hi, thanks

Best regards
