### ISSUE TITLE
Error when trying to add user

### ISSUE THREAD

**Issue by elcsar18** [zgelici/FOS-Streaming-v1#39]
Can u help me.... when i enter to create a new user i get an error.
http://104.238.132.155:8000/manage_user.php 

admin:admin access..

**Comment by zgelici** [comment]
Hello elcsar18,

Can you edit the file: manage_user.php
and adding the next code on the top

<?php
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);
?>

Than send me the error that you get.

good luck

**Comment by elcsar18** [comment]
Hi, where do i edit now the php files.... its no longer the /usr/local/nginx/html  route

**Comment by zgelici** [comment]
you can do it with putty or you can use winscp(https://winscp.net/eng/docs/lang:nl)

**Comment by elcsar18** [comment]
But i only get the root folder...
![captura](https://cloud.githubusercontent.com/assets/17571990/13433714/ba981c86-df98-11e5-89c1-b4460a52df31.PNG)

**Comment by zgelici** [comment]
click on this icon: 
![image](https://cloud.githubusercontent.com/assets/5995033/13433762/995ac29a-dfd3-11e5-8aee-8125bb646f66.png)

**Comment by elcsar18** [comment]
![captura](https://cloud.githubusercontent.com/assets/17571990/13433975/d3ad9be6-df99-11e5-8210-0f3ce750774f.PNG)

**Comment by elcsar18** [comment]
<option <?php echo e(in_array($category->id, $user->categories->lists('id')->toArray()) ? 'selected' : ''); ?> value="<?php echo e($category->id); ?>"><?php echo e({ $category->name); ?>
 


thats that line

**Comment by zgelici** [comment]
i updated the code

you need to replace your the code from views/manage_user.blade.php  with this one

https://github.com/zgelici/FOS-Streaming-v1/blob/master/views/manage_user.blade.php

**Comment by elcsar18** [comment]
Great, its now working :D 

I also send you a mail, i can help with the Spanish Translation if you want.

**Comment by zgelici** [comment]
Hi elcsar18,

Great that you fixed it. Thanks
