### ISSUE TITLE
Dasboard issue

### ISSUE THREAD

**Issue by Goldtrak** [zgelici/FOS-Streaming-v1#4]
Hi,

I try to click in Dashboard menu but nothing work.

Could you please check?

Thanks best regards

**Comment by edyee** [comment]
its working now just upgrade it

**Comment by edyee** [comment]
i have updated wiki you can find how to update your fos to fix this

**Comment by zgelici** [comment]
@edyee  okey
@edyee I dont understand you: "i have updated wiki you can find how to update your fos to fix this"
