### ISSUE TITLE
What type of transcoder i need...

### ISSUE THREAD

**Issue by elcsar18** [zgelici/FOS-Streaming-v1#41]
What type of transcoder configuration do i need for channels like this one?
http://dreamshows.ddns.net:8081/live/scandi/scandi/1312.ts

i test it with the 2 default configuration and didnt work.. also with a config i found on a youtube video and also didnt work

**Comment by zgelici** [comment]
i see you fixed it?

**Comment by elcsar18** [comment]
No, i delete them from the panel, because they didnt work
