### ISSUE TITLE
No Activities

### ISSUE THREAD

**Issue by Jamezy92** [zgelici/FOS-Streaming-v1#44]
When I Look In The Activity Table In PHPMyAdmin Their Are Lots Of Records, When I Look ON The Activities In The Admin Panel The List Is Empty.

Could You please Advise?

**Comment by zgelici** [comment]
Hi Jamezy92

The activities is for when you are watching a channel, than you can see the actvity.(see your online users). but this function doesnt work well on some server configurations.

**Comment by Jamezy92** [comment]
Zegelici, the code was wrong in the Activities.php Page, it was set to 0000-00-00 00:00:00 when it needs to be NOT EQUAL TO, This was changed and the activities are now showing.

**Comment by zgelici** [comment]
Nice :)
