### ISSUE TITLE
Unable To Stream

### ISSUE THREAD

**Issue by Jamezy92** [zgelici/FOS-Streaming-v1#45]
Hey Guys,

Just installed FOS Streaming Panel, I Have Everything Set Up Correct (I Presume I Followed The Instructions Correctly.)

I Can Log In, I Have Created A User With A Limit of 5 Connections.

When I Originally Setup The Panel, I Didn't Get The Default Transcoders I Hade To Create My Own. (Not Sure If I Did Something Wrong).

When I Add A Stream I Have Done The Follow:

Entered Stream Name As: **BT Sport**
Entered Streamurl As: **http://iptvbox.noip.us:9998/live/*******/*******/700.m3u8 **(*** = Username/Password)
Selected: **Bit stream filter**
Chosen Category As: **Sports**
Transcoder Profile: **Audio Copy and Video Copy** (Created Myself).

When I Open The Stream: http://server.thedantv.co.uk:8000/live/*****/*****/2 Using VLC I Get Nothing When I Browse To This Address In A Browser I Get A Blank Page.

If I Select The PROXY Tick Box On The Stream, The Stream Works (However, It Looks Like Its Just Doing A Redirect To The StreamURL. Not ReStreaming)

If I Browse To The URL In A Browser With PROXY Selected I Get The Following:

`
#EXTM3U 
#EXT-X-VERSION:3 
#EXT-X-TARGETDURATION:12 
#EXT-X-MEDIA-SEQUENCE:927 
#EXTINF:8.000000, http://iptvbox.noip.us:9998/streaming/clients_live.php?extension=m3u8&username=*****&password=*****&stream=700&type=hls&segment=700_927.ts
#EXTINF:9.240000, http://iptvbox.noip.us:9998/streaming/clients_live.php?extension=m3u8&username=*****&password=*****&stream=700&type=hls&segment=700_928.ts 
#EXTINF:10.720000, http://iptvbox.noip.us:9998/streaming/clients_live.php?extension=m3u8&username=*****&password=*****&stream=700&type=hls&segment=700_929.ts 
#EXTINF:11.880000, http://iptvbox.noip.us:9998/streaming/clients_live.php?extension=m3u8&username=*****&password=*****&stream=700&type=hls&segment=700_930.ts 
#EXTINF:8.000000, http://iptvbox.noip.us:9998/streaming/clients_live.php?extension=m3u8&username=*****&password=*****&stream=700&type=hls&segment=700_931.ts 
#EXTINF:11.760000, http://iptvbox.noip.us:9998/streaming/clients_live.php?extension=m3u8&username=*****&password=*****&stream=700&type=hls&segment=700_932.ts
`

Why Am I Unable To ReStream Myself As I Can Only Get Streams To Work If I Choose The Proxy Option When Adding The Stream.

PLEASE HELP!

**Comment by zgelici** [comment]
On the end of this week i will check this.

**Comment by Jamezy92** [comment]
Thank You If You Require A Login To The Panel Let Me Know If You Would Like To Check I Have Everything Setup, I Could Give SSH Access :+1: .. I Presume I Have Everything Set Up But When I Watched The Tutorial On YouTube, The Seemed To Have 2 Default Transcode Settings, Which I Had None.

ALSO Is Proxy Just Another Word For ReStream As In The Database The Field Is Name ReStream.

**Comment by zgelici** [comment]
Can you send a mail info@tyfix.nl?
