### ISSUE TITLE
How to start fos-streaming at boot ?

### ISSUE THREAD

**Issue by messi89** [zgelici/FOS-Streaming-v1#49]
Hi

After reboot the fos-streaming are not executed automaticaly

I try to start nginx_fos (on nginx/sbin directory) but I have a not found error on http://ip:8000

**Comment by zgelici** [comment]
Manual starting: 
/home/fos-streaming/fos/php/sbin/php-fpm
/home/fos-streaming/fos/nginx/sbin/nginx_fos

This must be below in /etc/rc.local, if it isn't there. Otherwise you can try to add it inside 
/etc/init.d/rc.local
