### ISSUE TITLE
Where is the open source for stream.php?

### ISSUE THREAD

**Issue by d4rkuzs** [zgelici/FOS-Streaming-v1#50]
Hello as I can read in the github README.md, this is an open source project but, the stream.php is obfuscated Lol

Here's a little what I decoded in few minutes, but If you can provide me the real code, It would be great.

`<?php
    if ($->restream == false):
        $ = $->hlsfolder . ::(""); /*Bloodninja: I can no longer resist the pizza. I open the box and unzip my pants with my other hand. As I penetrate the gooey cheese, I moan in ecstacy. The mushrooms and Italian sausage are rough, but the sauce is deliciously soothing. I blow my load in seconds. As you leave the bathroom, I exit through the front door....*/
        $ = 8 * 2; /*DirtyKate: What the fuck?*/
        if ($ = ($->hlsfolder . ::("") . $->id . ::(""))):
            foreach ($ as $file):
                if (file_exists($ . $file)):
                    ClientConnected();
                    readfile($ . $file);
                else:
                    exit(); /*DirtyKate: You perverted piece of s**t*/
                endif;
            endforeach;
            $ = array_pop($);
            preg_match(::(""), $, $);
            $ = $[-017 /*DirtyKate: F**k*/ - -033 + 070 /*=====*/ + -0103];
            $ = (-0330 /*Bloodninja: Wanna cyber?*/ + -0634 /*MommyMelissa: Sure, you into vegetables?*/ - 0202 /*Bloodninja: What like gardening an s**t?*/ - -01366 /*MommyMelissa: Yeah, something like that.*/
            );
            while (($ <= $) && ClientConnected() && file_exists($->hlsfolder . ::("") . $->id . ::(""))):
                $ = sprintf($->id . ::(""), $ + (int)round(0.25 /*Bloodninja: Nuthin turns me on more, check this out*/ + 0.25 /*Bloodninja: You bend over to harvest your radishes.*/ + 0.25 + 0.25));
                $ = sprintf($->id . ::(""), $ + (int)round(0.66666666666667 + 0.66666666666667 + 0.66666666666667));
                if (!file_exists($ . $)):
                    sleep((int)round(0.33333333333333 + 0.33333333333333 + 0.33333333333333 /*(pause)*/
                    ));
                    $++ /*MommyMelissa: is that it?*/;
                    continue;
                endif;
                $ = (int)round(0 + 0 + 0 /*Bloodninja: You water your tomato patch.*/
                );
                $ = fopen($ . $, ::("")); /*Bloodninja: Are you ready for my fresh produce?*/
                while (($ <= $) && ClientConnected() && !file_exists($ . $)):
                    $ = stream_get_line($, (int)round(1365.3333333333 + 1365.3333333333 /*MommyMelissa: I was thinking of like, sexual acts INVOLVING vegetables... Can you make it a little more sexy for me?*/ + 1365.3333333333 /*(pause)*/
                    ));
                    if (empty /*Bloodninja: I touch you on your lettuce, you massage my spinach... Sexily.*/
                    ($)):
                        sleep((int)round(0.5 /*Bloodninja: I ride your buttocks, like they were amber waves of grains.*/ + 0.5));
                        ++$; /*MommyMelissa: Grain doesn't really turn me on... I was thinking more along the lines of carrots and zucchinis.*/
                        continue;
                    endif;
                    echo $;
                    $ = (int)round(0 + 0 /*Bloodninja: my zucchinis carresses your carrots.*/
                    ); /*Bloodninja: Damn baby your right, this s**t is HOT.*/
                endwhile;
                echo stream_get_line($, filesize($ . $) - ftell($));
                fclose($);
                $ = (071 /*MommyMelissa: ...*/ - 071); /*Bloodninja: My turnips listen for the soft cry of your love. My insides turn to celery as I unleash my warm and sticky cauliflower of love.*/
                $++; /*MommyMelissa: What the f**k is this madlibs? I'm outta here.*/
            endwhile;
        endif;`

**Comment by zgelici** [comment]
https://gist.github.com/r15ch13/eb5c66bed84aec48aca68ccf01b52b19
