### ISSUE TITLE
Unable to add users blank screen.

### ISSUE THREAD

**Issue by ant0spy0binns** [zgelici/FOS-Streaming-v1#51]
It appears the latest update breaks the capability of adding users and when you click on add users it loads up with a blank screen error 500

**Comment by homes22** [comment]
same problem !!! place fix !!!

**Comment by zgelici** [comment]
Can yousend me an email(info@tyfix.nl). i need to see the bug.

**Comment by ant0spy0binns** [comment]
ok i have emaild you.

**Comment by zgelici** [comment]
ant0spy0binns there was an issue in the add user part. its fixed now.

Thanks
