### ISSUE TITLE
Getting errors from stream.php after restart

### ISSUE THREAD

**Issue by yrck** [zgelici/FOS-Streaming-v1#52]
Everything works after install on Ubuntu 14.04, but after restart stream.php starts throwing an error:

PHP message: PHP Fatal error:  Class name must be a valid object or a string in /home/fos-streaming/fos/www/stream.php(15) : eval()'d code on line 1" while reading response header from upstream

Appears that the obfuscated class at line 15 in stream.php is to blame.

When you decode it theirs some nasty comments and it looks like poorly written php.

I tried switching versions around to see if it was an issue with the default 5.5 version on Ubuntu 14, also tried symlinking to the 5.6.13 version in the FOS directory.

**Comment by zgelici** [comment]
i will publish the stream.php

**Comment by yrck** [comment]
Thank you.

The published code looks really clean and is working for me.
