### ISSUE TITLE
fresh install no work

### ISSUE THREAD

**Issue by PlintuZz** [zgelici/FOS-Streaming-v1#53]
clean ubuntu 14.04 fresh install not work
clean ubuntu 16.04 fresh install not work
r15ch13 docker install - work

**Comment by zgelici** [comment]
Thanks for your message,

code is updated

**Comment by PlintuZz** [comment]
clean ubuntu, official repo, no update php to ver 5.6

  Problem 1
    - illuminate/database v5.3.4 requires php >=5.6.4 -> your PHP version (5.5.9) does not satisfy that requirement.
    - illuminate/database v5.3.0 requires php >=5.6.4 -> your PHP version (5.5.9) does not satisfy that requirement.
    - Installation request for illuminate/database ^5.3 -> satisfiable by illuminate/database[v5.3.0, v5.3.4].

**Comment by iPrinz96** [comment]
i have the same Problems with ubuntu.
And with Debian i have an curl (7) error
