### ISSUE TITLE
Installing PHP File Failed

### ISSUE THREAD

**Issue by iPrinz96** [zgelici/FOS-Streaming-v1#54]
Server Details:
KVM Server by Serverbiz.net
HDD; 30GB
System: Debian 7.3.0 Wheezy 32 Bit
Ram: 512 MB
Clean install.

My Problem
(See Pictures)

![installing fail2](https://cloud.githubusercontent.com/assets/22468685/18889601/f3a33cbc-84fd-11e6-95a2-7b1a4a891a79.PNG)

**Comment by iPrinz96** [comment]
![installing fail](https://cloud.githubusercontent.com/assets/22468685/18889610/ff14307e-84fd-11e6-80a3-217ac95485ae.PNG)

**Comment by iPrinz96** [comment]
With Debian 7 64Bit, Debian 8 64Bit
And Raspberry pi (Based on Debian 6 or 7. idk.)
I have a curl (7) connectet fail to port 8000: connect refused

With Ubuntu i have more Problmes..

**Comment by iPrinz96** [comment]
And her the fail message with my Raspberry pi

![raspberry pi fail](https://cloud.githubusercontent.com/assets/22468685/18889880/45088e94-84ff-11e6-8b61-ca767fd42517.PNG)

**Comment by Stefanoz45** [comment]
libpng.12.so error:
```
 sudo apt-get install libpng12-0
```

**Comment by iPrinz96** [comment]
Thx. I test it.

**Comment by iPrinz96** [comment]
Is the same problem. Must i reboot the system now?

**Comment by Stefanoz45** [comment]
Try to reboot and restart nginx service

**Comment by iPrinz96** [comment]
How i restart the nghix service?

**Comment by Stefanoz45** [comment]
```
su root
service nginx restart
```

**Comment by iPrinz96** [comment]
I was only logged in with root (but only with my test server)

**Comment by iPrinz96** [comment]
I test it again

**Comment by iPrinz96** [comment]
i have reinstall the serve but this error come again..

> 3. [Installing needed files:] [#####sh: 1: Syntax error: Unterminated quoted string

**Comment by iPrinz96** [comment]
Next Problem.

> [Installing needed files:] [#####sh: 1: Syntax error: Unterminated quoted string
Is fixed.
But i have a new Problem..

![new fail](https://cloud.githubusercontent.com/assets/22468685/18987519/49b4aae0-8702-11e6-8b44-09e523b32083.PNG)

**Comment by sevano** [comment]
We have fixed everything
this works now: 
wget http://fos-streaming.com/fresh_install.sh
chmod 755 fresh_install.sh
./fresh_install.sh

**Comment by iPrinz96** [comment]
Its work on ubuntu 14.
I Test it again on Debian 8.
Thx i love ur Team :D

**Comment by sevano** [comment]
great :) I'm sorry for the delay.

**Comment by iPrinz96** [comment]
Its no Problem :)
I have open a new issue with a new Problem with streams :(
