### ISSUE TITLE
libjpeg.so.8: cannot open shared object file

### ISSUE THREAD

**Issue by emresen** [zgelici/FOS-Streaming-v1#55]
Hi,

i need help by installing fos-streaming-v1 on debian 6. everything run's clean but if i try to execute /home/fos-streaming/fos/php/sbin/php-fpm, i get the following error:

/home/fos-streaming/fos/php/sbin/php-fpm: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

i've tried a lot of apt-get remove and install again but nothing helps.

**Comment by sevano** [comment]
Why u are using debian 6, if i may ask? I didnt test it out on that version. If you want provide me the login details from ssh, so i can take a look. 

Contact email: info@tyfix.nl

**Comment by Stefanoz45** [comment]
64bit: https://github.com/maciej-c/libjpeg8x64
paste libjpeg.so.8 on /lib/x86_64-linux-gnu/libjpeg.so.8
