### ISSUE TITLE
Streams Dosent Work

### ISSUE THREAD

**Issue by iPrinz96** [zgelici/FOS-Streaming-v1#56]
My Stream dosent work.
what am I doing wrong?
Edit: Pictures was deleted

**Comment by sevano** [comment]
The date wasnt correct so it was expired, you can test it open it in your browser like this
http://ip:8000/live/ipetetz/hytt4/206

By the way if possible remove ip and logins details from this ticket, because everyone can see it. 
Next time mail those details to info@tyfix.nl

**Comment by iPrinz96** [comment]
Its work *.*
What i have do wrong?

**Comment by sevano** [comment]
we have one common problem with user limit, and the other reason what can block is the expire date. 
And don't thick proxy

**Comment by iPrinz96** [comment]
For what is Proxy?

**Comment by didiugo** [comment]
I did love the panel but only allowed me connect 4 user  for example 1 user setup for 10 connection  when I connect 4 is fine but when. I connect 5 the panel  freeze and don't let me long in  if I stop the the connection 5 the panel back to normal  any help pleaSent I do.have the new version on

**Comment by zgelici** [comment]
We are creating a new installation script

We also updated some scripts,than we hope this issue is solved.
