### ISSUE TITLE
Every few seconds i need to restart stream

### ISSUE THREAD

**Issue by gigo1988** [zgelici/FOS-Streaming-v1#59]
Hello My issue is i put a stream and start a user to watch this stream. everything work withou transcoding. than after few second i need to restart the stream but i dont now the reason. If i start sthe stream direct without in vlc it works fine.

**Comment by Stefanoz45** [comment]
Transcode type
Video: Copy Audio: Copy
It works fine for me

**Comment by TRC4** [comment]
and for massive start/stop streams show the msg

An error occurred.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.

**Comment by zgelici** [comment]
This has been fixed
