### ISSUE TITLE
user blocked every time when change channel

### ISSUE THREAD

**Issue by adilabd** [zgelici/FOS-Streaming-v1#6]
solucion : permit 10 or more max connection

please fix

**Comment by zgelici** [comment]
Hello adilabd,

Thank you for your report. For now you can better set the limit on 0. (than you dont have that problem)

We will find a solution for it.

Can you send a email to info@tyfix.nl. Maby you can help us to solve the problem.

**Comment by zgelici** [comment]
@adilabd  i think that you server is missing something. We are trying to detect the problem.

**Comment by zgelici** [comment]
Hello adilabd,

We found the issue, we are trying to fix it.

Thanks

**Comment by cyclone76** [comment]
Hi,
I use FOS panel, founding on multicsinfo for a week.
I tested others panels before and you is very well.
I use your apk softawre on my android phone too.
I want to as you some questions :
0/ my bigger problem is that i cannot the the users list. there is a problem with users.php
I only can see the first users but they are all into phpmyadmin and work.
When i install the panel, at the beginning, i see the users. But after a few minutes they disapear !
So to modify an user or delete it i have to go to phpmyadmin.
I tried the panel on many Ubuntu distributions (12.04 <–> 15.10) and on a lot of fresh servers.
I used Windows 7, 8, 10, IE, Chrome and Firefox.
1/ What is the proxy function whe i add a channel. is it to appear on the connector server with another IP than my server’s IP ?
2/ Is it necessary to use the transcode profile abnd fpor what to do ?
3/ What is beat stream filter used for ?
Thanks for all

**Comment by zgelici** [comment]
Hallo cyclone76,

That is weired, can you show that users.php problem?

1. the proxy function redirects is a redirection to an another server
2. yes, because ffmpeg needs  a configration. copy copy is the most using transcode setting
3. its for malformed streams.
