### ISSUE TITLE
Transcoding

### ISSUE THREAD

**Issue by zlatko11** [zgelici/FOS-Streaming-v1#67]
Hello , why when i am trying to transcode , or create new transcode profile nothing happends? transcoding doesnt work

**Comment by zgelici** [comment]
Do you have more information, what exactly doenst work. add transcode? using the transcode profile?

**Comment by zlatko11** [comment]
When i choose transcoding existing profile who comes default with fos panel doesnt work, when i try to create new one also happend. I can create profile but when i choose on some channel nothing happends, channel is on default resolution , bitrate , etc ....

**Comment by zgelici** [comment]
The problem is:

You want so select the new transcode profile, but it doesnt save on the stream page? it doesnt change?

**Comment by zlatko11** [comment]
Yes. The stream works same like original, nothing has changed

**Comment by zlatko11** [comment]
I am going , streams-addstream-choose category-choose transcoding profile and add. Then when i go to play in vlc stream is same like original, nothing happend

**Comment by zgelici** [comment]
when you go to that stream, the transcode profile is not on the default? i'm trying to locate problem. is it in stream.php or in manage_stream.php

**Comment by zgelici** [comment]
Can you go to functions.php, go to line: 112: return $ffmpeg;

add before this line: print_r($ffmpeg);
than click on start stream.

**Comment by zlatko11** [comment]
https://s24.postimg.org/66nwknin9/dfdfdfdfdfd.jpg

This is how look when i am adding or edit channel , i can choose transcode profile but nothing happends in vlc

**Comment by zlatko11** [comment]
i fix this

Can you go to functions.php, go to line: 112: return $ffmpeg;

add before this line: print_r($ffmpeg);
than click on start stream.

Its the same, nothing happends

**Comment by zlatko11** [comment]
https://s29.postimg.org/nkvjtxtsn/fgfgfgfgf.jpg

**Comment by zgelici** [comment]
can you provide me the login to your panel?

http link: 

Dont post it here, you can better sent it to:
info@tyfix.nl

**Comment by zgelici** [comment]
and add before: print_r($ffmpeg);
this
print_r($trans);

**Comment by zlatko11** [comment]
Ok check your email
