### ISSUE TITLE
fos streaming limit user 4 with more not work

### ISSUE THREAD

**Issue by spektatorbord** [zgelici/FOS-Streaming-v1#68]
i hav test fos streaming  i cant use 5 or mor client user in that panel the fos streaming not work
cant acces in the panel .5 user conected work fine   when the 6 user is conected the fos panel is blocked not work  the the 6 user cant conected

**Comment by zgelici** [comment]
Hi Spektatorbord,

Soon i will update the code.

**Comment by spektatorbord** [comment]
its really not work more than 4 or 5 conection he blocked the  the admin panel not work 
the listen port server 8000 not work,the apache server work but nginx 8000 listen port is block,,,but the 4 or 5 conection work abaut 30 miut and after go anything in block crash,,you restart the server to rapir that,,,when you reconect the 4 client or 5 client user,,that 4 or 5 conection work fine but you cant use admin panel you cant conect another user the port 8000 not acept conections,,,,that is  a litle problem for the best iptv panel at the momet please repair that thanky so mutch team fos streaming

**Comment by spektatorbord** [comment]
wow i hav test the fos treaming with 4 core processor and  16 giga ram   the same problem fos streaming not work with mor 5 user conected on the server...dont6 work panel control dont work nathing,cant conect the 6 user ,
the conlusion when the 5st user conected on the fost streaming ,the panel control blocked,not work the port 8000 not work the apasche port80 work but fos streaming is blocke ,,in the same moment  the 5 work stream fine but the fos panel is blocket to receiver another operation.,.....its bug its simply bug...can you repair,,thanky

**Comment by sentest** [comment]
this is all down the php-fpm and the nginx workers

**Comment by spektatorbord** [comment]
now what can we do?the fos striming not work with mor 5 conection user ,the user panel  not work,
is limit>?

**Comment by sentest** [comment]
A patch shall be uploaded when the lead developer gets online the patch has
been done and tested already

**Comment by spektatorbord** [comment]
link?

**Comment by spektatorbord** [comment]
sorry what is the logic,,,,iptv admin panel to restream  5 user
sorry you create a panel iptv server limited,,in 2 years fos streaming life work with 5 user?

**Comment by sentest** [comment]
It's a bug within last release it's not affecting all users

**Comment by spektatorbord** [comment]
i havent installl 30 google servers to test it,,the all server with fos panel old and v1   not work with mor 5 user ,,,the panel blocked .the port 8000 go in crasch,,,

**Comment by zgelici** [comment]
Hello sentest, 

do you have the patch?

**Comment by sentest** [comment]
Sent you the files earlier

**Comment by zgelici** [comment]
Can you resent it?

did you sent it from skype?

**Comment by sentest** [comment]
i did indeed

**Comment by zgelici** [comment]
Can you sent me an message. i dont know your Skype username.

**Comment by zgelici** [comment]
@sentest Thanks

@spektatorbordI: didnt test it:

Can you follow the next commands:
1. go to the fos-streaming path
2. git pull
3. php fix_conf_files.php

**Comment by spektatorbord** [comment]
i dont know what is that git pull not work
fosstreaming havent problem to work with 5 user+

**Comment by spektatorbord** [comment]
idont understand that procedur

    go to the fos-streaming path
    git pull
    php fix_conf_files.php

where is the path
?
