### ISSUE TITLE
Error on dashboard

### ISSUE THREAD

**Issue by seanosd** [zgelici/FOS-Streaming-v1#69]
Have just installed the panel and all seemed to be well. Logged into the dashboard and got thr white screen of death. Logs are showing 👍 

/home/fos-streaming/fos/logs/error_log

2017/02/14 13:47:17 [error] 12453#0: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'logourl' doesn't have a default value' in /home/fos-streaming/fos/www/vendor/illuminate/database/Connection.php:480
Stack trace:
#0 /home/fos-streaming/fos/www/vendor/illuminate/database/Connection.php(480): PDOStatement->execute()
#1 /home/fos-streaming/fos/www/vendor/illuminate/database/Connection.php(754): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `se...', Array)
#2 /home/fos-streaming/fos/www/vendor/illuminate/database/Connection.php(717): Illuminate\Database\Connection->runQueryCallback('insert into `se...', Array, Object(Closure))
#3 /home/fos-streaming/fos/www/vendor/illuminate/database/Connection.php(481): Illuminate\Database\Connection->run('insert into `se...', Array, Object(Closure))
#4 /home/fos-streaming/fos/www/vendor/illuminate/database/Connection.php(435): Illuminate\Database\Connection->stat" while reading response header from upstream, client: 62.249.248.68, server: , request: "GET /dashboard.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php__5-fpm.sock:", host: xx.xx.xx.xx

Running Ubuntu 16.04 

Any help would be great.

Cheers

**Comment by zgelici** [comment]
Hi seanosd ,

I think your mysql isnt running

try this command:
sudo start mysql

**Comment by seanosd** [comment]
Thanks for coming back to me.

The MYSQL database was already started as I had checked this, Think there was an error on the initial setup so I set up a new LEMP stack and ran it again and all is fine now.

Thanks for the help.
