### ISSUE TITLE
FOS STREAMING WORK  YES O NO WITH MOR 5 USER??????

### ISSUE THREAD

**Issue by spektatorbord** [zgelici/FOS-Streaming-v1#70]
I AM TESTED FOS STREAMING PANEL ,WHEN YOU CONECT 5 USER  WITH THE SERVER  IPTV  YOUR PANEL GO IN BLOCK NOT WORK,I HAVENTTESTED ON GOOGLE SERVERS 1 CORE 2 CORE 4 CORE ,2-4-6-8-12 GIGA RAM THE NETWORK 160 MEGABYTE DAWNLOAD AND 100 MEGABYTE UPLOAD THA FOS PANEL NOTWORK WITH MOR 5 CONECTION YOUR SERVER NOT WORK,WHEN THE5 CONECTION USER WORK FINE BUT THE SERVER IS BLOCKED CANT AKSES ON THE ADMIN PANEL,NOT PING,,,AHA
NOW I ASKED THE FOS STREAMING PANEL ITS SO BEATIFUL SO FINE PANEL SO FAST SO EKSELENT,,,,ITS POSIBLE ALLL WORK OF TEAM GROUP FOS PANEL LOS POPULARITY WITH THAT BUG,,,,,,,
NOW I CALL YOUR SUPORT ALL DEVELOPER]
 REPAIR THAT STUPID BUG

**Comment by zgelici** [comment]
Hello Spektatorbord,

We are trying to solve it. We think Stream.php is the big problem.

TIP: I am the only developer at this moment.
