### ISSUE TITLE
old fos panel is the best vs v1

### ISSUE THREAD

**Issue by spektatorbord** [zgelici/FOS-Streaming-v1#74]
i havent test mor dhen 100 reinstallation of fos panel
the old is the best

4000 stream work 
no freez
no crasch
no change channel evry 20or40 second of the userv in vlc
its beter old pannel vs v1 because v1 not suport more 1000 channel  isent instable on the diferent installation in clean ubuntu servers
the v1 is not similar with old panel in erformance
but the 2 version old and v1 not suport more 5 user conectet in the same time go in crasch  ,after the 5user disconect the pannel work fine when the 5 user conected the anel not resonde more comand blocked

incremet the caacity to work in more 2000stream
increment the fos to work more  user 5+
reair the bug in streaming to not change the channel evry 40second in vlc user client
ad the buton to view more streams not100
thanky please repair fos streaming is instable

**Comment by zgelici** [comment]
Hello spektatorbord,

I read all your commets before, i didnt like your comments. but your tests are good. The reason why v1 has this performance issue is because of the limit, but i solved it. soon i will release it. Than you can test v1 without performance issues.

**Comment by spektatorbord** [comment]
ihavent tested but is instable,,,,,and sorry for my en langue ,,i am from albania,,,,,,
the old panel are very stable

the problem in old anel dont have the client 1 user option 
and cant use more 5 uuser conection the panel is blocked,thanky so mutch

**Comment by zgelici** [comment]
No problem, i updated the source but i didnt test the install script. tomorrow i can test it.

**Comment by spektatorbord** [comment]
YESSSSSSSSSSSSSSSS
THE BLANK PAGE PROBLEM RESOLVED 
OK NOW WE TEST ALL BUGS I INFORM YOU  ,,,,AFTER THEST ,ANYTHING IS OK ,,THANKY SO MUTCH  FOR YOUR SUPER WORK SUPER PROFESIONAL ,,,,,,,,,,,,,,A GOOOD   DAY

**Comment by zgelici** [comment]
No problem

Sorry, but it was not professional, thank you for your tests.

**Comment by spektatorbord** [comment]
![capture](https://cloud.githubusercontent.com/assets/25746786/23211934/9ea24b1a-f904-11e6-995c-1fdaa2917728.PNG)
yes you are resve the problem with multiple user,.,,,,,,,,,,,,sooo goood
now i test all bug and report ok thanks so mutch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
