### ISSUE TITLE
installation 50 percent

### ISSUE THREAD

**Issue by spektatorbord** [zgelici/FOS-Streaming-v1#75]
![capture](https://cloud.githubusercontent.com/assets/25746786/23119749/bf9612c2-f759-11e6-90d8-23f79e1d3f6f.PNG)
uvuntu 14 and 16 lts

**Comment by spektatorbord** [comment]
ubuntu 12
![capture](https://cloud.githubusercontent.com/assets/25746786/23124202/20f187e2-f76c-11e6-8a7f-8a3631bb9945.PNG)

**Comment by spektatorbord** [comment]
clean ubuntu server 12 14 16 wont to install panel

**Comment by spektatorbord** [comment]
havent testes buntu 12 14  16 in clean maschine,,,,,,imposible to install

**Comment by keysersoze1977** [comment]
I have the same issue.  can anyone help?

**Comment by spektatorbord** [comment]
![capture](https://cloud.githubusercontent.com/assets/25746786/23130813/29e61a22-f788-11e6-8fc4-9a35cb0f01bc.PNG)

**Comment by spektatorbord** [comment]
imposible install

**Comment by spektatorbord** [comment]
![capture](https://cloud.githubusercontent.com/assets/25746786/23130939/8822441c-f788-11e6-868f-373e7916ec3b.PNG)

**Comment by spektatorbord** [comment]
![capture](https://cloud.githubusercontent.com/assets/25746786/23131035/da6a4116-f788-11e6-81f1-618db9b45426.PNG)

**Comment by spektatorbord** [comment]
![capture](https://cloud.githubusercontent.com/assets/25746786/23131084/08197136-f789-11e6-9ef2-ac0a3221107b.PNG)

**Comment by spektatorbord** [comment]
the instalation script is incorect  mey be,,,its imposible to installl

**Comment by zgelici** [comment]
Thank you, did you install it on a fresh machine?

**Comment by spektatorbord** [comment]
i havent install in a fresh maschine 
ubunutu 12 14 16

**Comment by spektatorbord** [comment]
now is another problem a old v1 when installl fresh on fresh ubuntu maschine  the panel havent white page after put the username the password

**Comment by zgelici** [comment]
Do you have skype?

**Comment by spektatorbord** [comment]
nooo

**Comment by spektatorbord** [comment]
i havent install the new 
wget https://raw.githubusercontent.com/zgelici/FOS-Streaming-v1/master/install.sh

that not installing the pannel,,ngnix,,,,,,,and fos streaming directori
the photo you can see the mising mkdir home/fospanel/www.........

**Comment by zgelici** [comment]
i updated the script

**Comment by spektatorbord** [comment]
okn  now i create ubuntu server in google cloud i test it 5 minutes//////

**Comment by spektatorbord** [comment]
iiiiii
i havent installed 
but i havent big problem with all my fos streaming
old pannel ande the v1 old

and the new  panel intalation is complete but cant sseee it i havent white page
![capture](https://cloud.githubusercontent.com/assets/25746786/23143126/07962ca4-f7c0-11e6-8663-e8b07141e6fd.PNG)

**Comment by spektatorbord** [comment]
i dont now the problem is withmy all browser or no

can you goo to the pannel now and see that work or no
with this ip on the foto

**Comment by spektatorbord** [comment]
white blank page
with all my browser
ie  firefox    crome tor

**Comment by zgelici** [comment]
can you check your error.log?

**Comment by spektatorbord** [comment]
dont have error logo
can you go on this 
http://130.211.68.111:8000/
its fresh installl
can you see work o no the panel
in my all browser see blank page after i insert admin admin

**Comment by spektatorbord** [comment]
good night,,,letso work tomorrow

**Comment by zgelici** [comment]
good night

**Comment by spektatorbord** [comment]
i havent isntall fos on ubuntu in my local pc,,,in buntu i have the same problem,fos panel after insert user password   ,,not work   blank page
![capture](https://cloud.githubusercontent.com/assets/25746786/23165321/d5f58088-f83b-11e6-8f5b-c764aec6b710.PNG)

**Comment by spektatorbord** [comment]
first  and after
![capture](https://cloud.githubusercontent.com/assets/25746786/23165367/1594c604-f83c-11e6-8909-0c3c9becb25e.PNG)
![capture](https://cloud.githubusercontent.com/assets/25746786/23165387/2b382a82-f83c-11e6-879e-bf604e6fb1da.PNG)

**Comment by spektatorbord** [comment]
and the same problem i have in a old panel now,,,cant acces of my fos panel after inser credencial,,,the beautiful is,,,,when i atachet m3u onvlc the client on my old fos panel work see the streaming,but its iposible to acces on the fos paneladmin blanc page

**Comment by spektatorbord** [comment]
i have install now the volume 0 and work fine,,,,,,,on gcloud,,but v1 havent blank page when insert user pasword and press enter

**Comment by spektatorbord** [comment]
the new https://raw.githubusercontent.com/zgelici/FOS-Streaming-v1/master/install.sh
istalation is ok
user password  all ok
when finish install 
![capture](https://cloud.githubusercontent.com/assets/25746786/23169498/3de20f94-f84c-11e6-866a-aee38917cef4.PNG)
and when you go on admin panel   insert the user and password  you se the admin page blank
![capture](https://cloud.githubusercontent.com/assets/25746786/23169542/69066120-f84c-11e6-8a93-af8f101a97d6.PNG)
the problem is persist in 10 fresh instalation on gcloud and local pc ,,with fresh ubuntu server,,in 12 14 16

**Comment by zgelici** [comment]
I am now fixing one installation for ubuntu 14

**Comment by zgelici** [comment]
@spektatorbord  can you test the new installation on a ubuntu server?

**Comment by amidevous** [comment]
recomand use mysql file for import database

and dot not use php file for installation

bash file avanced with detect system view sentora panel project

https://github.com/sentora/sentora-installers

**Comment by zgelici** [comment]
@amidevous thank you

**Comment by spektatorbord** [comment]
![capture](https://cloud.githubusercontent.com/assets/25746786/23199393/5f58ad36-f8ce-11e6-9057-a0df1fcd1366.PNG)
new ubuntu fresh server 14 .04
idont understand after install ,,i go  to ip por  and insert user password
when press enter  admin panel wont to open
![capture](https://cloud.githubusercontent.com/assets/25746786/23199621/c195b4e8-f8cf-11e6-92a5-269393801666.PNG)
big bug

**Comment by zgelici** [comment]
@spektatorbord check your username, that is impossible an username with \ or /
