### ISSUE TITLE
I complete fresh installation...

### ISSUE THREAD

**Issue by WiggiX** [zgelici/FOS-Streaming-v1#76]
Hi, 
why the code is full of errors? I lost 1 hour to find it "..." :(
just to understand :)

**Comment by zgelici** [comment]
Sorry for the errors,

We are creating a new installation, installation is almost done. 

I did a wrong push to github. but the old installation has also some problems.

**Comment by VirgilioMicale** [comment]
Don't worry, I play with it!! :D

**Comment by zgelici** [comment]
:) The installation script has been changed, check the readme.

**Comment by VirgilioMicale** [comment]
:P
I install on vps centos the last one. But I ripete with new one! Good job
I like gentella, it's a good theme for project.
