### ISSUE TITLE
bug restart lose fos panel

### ISSUE THREAD

**Issue by spektatorbord** [zgelici/FOS-Streaming-v1#78]
when restart the server  when goto ip port 8000  fos not work 
dont have nathin conection on that,,,,not work

**Comment by spektatorbord** [comment]
sorry my friend.after restar fos panel the new instalation ubuntu 14x64bit    notwork

**Comment by zgelici** [comment]
i will check it, but i think php_fpm and ngnix is not started, try to start it manualy.

**Comment by spektatorbord** [comment]
comand please

**Comment by spektatorbord** [comment]
in terminal what is the comand line

**Comment by spektatorbord** [comment]
yesssssssssssss problem resolved
 php_fpm and ngnix     start manually   very gooddddddddd

**Comment by sevano** [comment]
Can you check if this is inside rc.local
/home/fos-streaming/fos/nginx/sbin/nginx_fos
/home/fos-streaming/fos/php/sbin/php-fpm

if yes, try to add those 2 lines inside 
/etc/init.d/rc.local

**Comment by spektatorbord** [comment]
thankyou so mutch
problem resolveed
