### ISSUE TITLE
Ubuntu fresh install not work

### ISSUE THREAD

**Issue by Mendim** [zgelici/FOS-Streaming-v1#79]
I tried on both 32 and 64 bit but not work
I installed by Docker
How to install the last version

Also an other bug.any user can acces here without login and can delete the logs.
http://ip:8000/activities.php

**Comment by spektatorbord** [comment]
8000/activities.php
Delete all logs
User 	Stream 	DataStart 	IP 	User agent 	Action

what is tha ,,,,,,,its more imortant that option?i dot uderstad that,..

**Comment by zgelici** [comment]
Thanks Mendim,

I fixed it, go to the fos folder (www)
run this command: git pull

@spektatorbord

too check who is what watching
