### ISSUE TITLE
Cron Jobs

### ISSUE THREAD

**Issue by sarelmx** [zgelici/FOS-Streaming-v1#9]
How put cron.php in crontab linux, in the readme say that cron is put manually,

**Comment by zgelici** [comment]
echo '*/2 * * * * www-data /usr/bin/php /home/fos-streaming/fos/www/cron.php' >> /etc/crontab

**Comment by sarelmx** [comment]
exelent thaks bro

**Comment by sarelmx** [comment]
Hi zgelici im interested in user front end and admin panel, i change 7 files to show only user panel now the code can show only user panel area, yo can acces in admin mode or in user mode,  
i include seek dbase with user or admin user, 

![fos](https://cloud.githubusercontent.com/assets/15387993/11135134/cff11d44-8967-11e5-880f-3d3482df2f79.png)

if you want i can send you all files, and you can view the change to implement in new version or update

**Comment by zgelici** [comment]
Hi sarelmx ,

Very nice, thanks. can you send the files or doing a pull request. Than i can look to it and publish it.

**Comment by sarelmx** [comment]
ok  i make one compress files and i send you to your personal mail..  my email is sarfut79@hotmail.com contact me please,
